spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/universiryDb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: admin
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  #Cloudinary Properties cloud
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
server:
  port: 8000