spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/universityDb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: admin
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /WEB-INF/views/
      suffix: .html
app:
  default:
    password: topsecret
server:
  port: 8000